BTRS/Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace BTRS.Models
{
    public class Login
    {
        [Required(ErrorMessage = "Required")]
        public string username { set; get; }

        [Required(ErrorMessage = "Required")]
        public string password { set; get; }
    }
}

BTRS/Controllers/BusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTRS.Data;
using BTRS.Models;

namespace BTRS.Controllers
{
    public class BusController : Controller
    {
        private readonly SystemDbContext _context;

        public BusController(SystemDbContext context)
        {
            _context = context;
        }

        // GET: Buses
        public async Task<IActionResult> Index()
        {
            ViewBag.Trip = _context.trip.ToList();
            return View(await _context.Bus.ToListAsync());
        }

        // GET: Buses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.Trip = _context.trip.ToList();
            if (id == null)
            {
                return NotFound();
            }

            var bus = await _context.Bus
                .FirstOrDefaultAsync(m => m.ID == id);
            if (bus == null)
            {
                return NotFound();
            }

            return View(bus);
        }

        // GET: Buses/Create
        public IActionResult Create()
        {
            ViewBag.Trip = _context.trip.ToList();
            return View();
        }

        // POST: Buses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection form)
        {
            int adminID = (int)HttpContext.Session.GetInt32("adminid");

            string captain_name = form["captain_name"];
            int numOfSeats = int.Parse(form["numOfSeats"]);
            int tripID = int.Parse(form["TripID"]);

            Bus bus = new Bus();
            bus.administrators = _context.administrators.Find(adminID);
            bus.captain_name = captain_name;
            bus.numOfSeats = numOfSeats;
            bus.trip = _context.trip.Find(tripID);

            _context.Bus.Add(bus);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Buses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.Trip = _context.trip.ToList();
            if (id == null)
            {
                return NotFound();
            }

            var bus = await _context.Bus.FindAsync(id);
            if (bus == null)
            {
                return NotFound();
            }
            return View(bus);
        }

        // POST: Buses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, IFormCollection form)
        {
            int adminID = (int)HttpContext.Session.GetInt32("adminid");

            string captain_name = form["captain_name"];
            int numOfSeats = int.Parse(form["numOfSeats"]);
            int tripID = int.Parse(form["TripID"]);

            //bus-id
            id = int.Parse(form["ID"]);

            Bus bus = _context.Bus.Find(id);

            bus.administrators = _context.administrators.Find(adminID);
            bus.captain_name = captain_name;
            bus.numOfSeats = numOfSeats;
            bus.trip = _context.trip.Find(tripID);

            _context.Bus.Update(bus);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Buses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            Bus bus = _context.Bus.Find(id);
            _context.Bus.Remove(bus);
            _context.SaveChanges();
            return RedirectToAction("Index");
            //return View();
        }

        // POST: Buses/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var bus = await _context.Bus.FindAsync(id);
        //    if (bus != null)
        //    {
        //        _context.Bus.Remove(bus);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool BusExists(int id)
        //{
        //    return _context.Bus.Any(e => e.ID == id);
        //}
    }
}

BTRS/Controllers/TripController.cs
using BTRS.Data;
using BTRS.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BTRS.Controllers
{
    public class TripController : Controller
    {
        private SystemDbContext _context;
        public TripController (SystemDbContext context)
        {
            this._context = context;
        }
        // GET: TripController
        public ActionResult Index()
        {
            return View(_context.trip.ToList());
        }

        // GET: TripController/Details/5
        public ActionResult Details(int id)
        {
            Trip trip = _context.trip.Find(id);
            return View(trip);
        }

        // GET: TripController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TripController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Trip trip)
        {
            try
            {
                int adminID= (int)HttpContext.Session.GetInt32("adminid");
                Administrators admin=_context.administrators.Where(a=>a.ID== adminID).FirstOrDefault();
                trip.administrators = admin;
                _context.trip.Add(trip);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TripController/Edit/5
        public ActionResult Edit(int id)
        {
            Trip trip = _context.trip.Find(id);
            return View(trip);
        }

        // POST: TripController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Trip trip)
        {
            try
            {
                _context.trip.Update(trip);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TripController/Delete/5
        public ActionResult Delete(int id)
        {
            Trip trip= _context.trip.Find(id);
            _context.trip.Remove(trip);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: TripController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

BTRS/Controllers/UserController.cs
using BTRS.Data;
using BTRS.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BTRS.Controllers
{
    public class UserController : Controller

    {
        private SystemDbContext _context;
        public UserController(SystemDbContext context)
        {
            this._context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
       
        
        public IActionResult signup()
        {
            return View();
        }
        [HttpPost]
        public IActionResult signup(Passengers passenger)
        {
            bool notempty = checkEmpty(passenger);
            bool duplicat = checkNoDuplicate(passenger);

            if (notempty)
            {
                if (duplicat)
                {
                    HttpContext.Session.SetInt32("passengerid", passenger.ID);
                    _context.passengers.Add(passenger);
                    _context.SaveChanges();

                    TempData["Msg"] = "the data was saved";
                    return RedirectToAction("TripList");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                TempData["Msg"] = "Please fill all input ";
                return View();
            }

        }


        public bool checkNoDuplicate(Passengers passenger)
        {

            Passengers passenger_username = _context.passengers.Where(u => u.username.Equals(passenger.username)).FirstOrDefault();
            Passengers passenger_phone = _context.passengers.Where(u => u.phone_number.Equals(passenger.phone_number)).FirstOrDefault();
            Passengers passenger_email = _context.passengers.Where(u => u.email_address.Equals(passenger.email_address)).FirstOrDefault();
            if (passenger_username != null)
            {
                TempData["Msg"] = "Please Change the username";
                return false;
            }
            else if (passenger_phone != null)
            {
                TempData["Msg"] = "Please Change phone number";
                return false;
            }
            else if(passenger_email != null)
            {
                TempData["Msg"] = "Please Change your email";
                return false;
            }
            else
            {
                return true;
            }
        }

        public bool checkEmpty(Passengers passenger)
        {
            if (String.IsNullOrEmpty(passenger.username)) return false;
            else if (String.IsNullOrEmpty(passenger.password)) return false;
            else if (String.IsNullOrEmpty(passenger.name)) return false;
            else if (String.IsNullOrEmpty(passenger.phone_number)) return false;
            else if (String.IsNullOrEmpty(passenger.email_address)) return false;
            else return true;
        }

        [HttpGet]
        public IActionResult login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult login(Login userlogin )
        {
            if (ModelState.IsValid)
            {
                string username = userlogin.username;
                string password = userlogin.password;

                Passengers passenger = _context.passengers.Where(u => u.username.Equals(username) &&
                u.password.Equals(password)).FirstOrDefault();

                Administrators admin = _context.administrators.Where(u => u.userName.Equals(username)
                && u.password.Equals(password)).FirstOrDefault();

                if (passenger != null)
                {
                    HttpContext.Session.SetInt32("passengerid", passenger.ID);
                    return RedirectToAction("TripList");
                }
                else if (admin != null)
                {
                    HttpContext.Session.SetInt32("adminid",admin.ID);
                    return RedirectToAction("tripOrBus");
                }
                else
                {
                    TempData["msg"] = "the user not found";
                    return View();
                }
            }
            else
            {
                TempData["msg"] = "please insert data";
                return View();
            }
        }
       
        public IActionResult TripList()
        {
            int passengerID = (int)HttpContext.Session.GetInt32("passengerid");
            List<int>lst_picked_trip=_context.passenger_Trip.Where(t=>t.passenger.ID.Equals(passengerID)).
                Select(u=>u.trip.ID).ToList();
            List<Trip>lst_unpicked_trip=_context.trip.Where(u=>lst_picked_trip.Contains(u.ID)==false).ToList();
            return View(lst_unpicked_trip);
        }
        public IActionResult AddTrip(int id)
        {
            int tripID = id;
            int passengerID=(int)HttpContext.Session.GetInt32("passengerid");
            Passenger_Trip passenger_trip=new Passenger_Trip();
            passenger_trip.passenger = _context.passengers.Find(passengerID);
            passenger_trip.trip = _context.trip.Find(tripID);
            _context.passenger_Trip.Add(passenger_trip);
            _context.SaveChanges();
            return RedirectToAction("pickedtrip_List");
        }
        public IActionResult pickedtrip_List()
        {
            int passengerID = (int)HttpContext.Session.GetInt32("passengerid");
            List<int> lst_trip = _context.passenger_Trip.Where(u => u.passenger.ID== passengerID).Select(s => s.trip.ID).ToList();
            List<Trip>lst=_context.trip.Where(t=>lst_trip.Contains(t.ID)).ToList();
            return View(lst);
        }
        public IActionResult delete_picked_trip(int tripID)
        {
            int passengerID = (int)HttpContext.Session.GetInt32("passengerid");
            Passenger_Trip passenger_trip = _context.passenger_Trip.Where(t => t.passenger.ID == passengerID && t.trip.ID == tripID).FirstOrDefault();
            _context.passenger_Trip.Remove(passenger_trip);
            _context.SaveChanges();
            return RedirectToAction("pickedtrip_List");
        }
        public IActionResult tripOrBus()
        {
            return View();
        }
    }
}

BTRS/Views/User/TripList.cshtml
@model IEnumerable<BTRS.Models.Trip>

@{
    ViewData["Title"] = "TripList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>TripList</h1>

<p>
@*     <a asp-action="Create">Create New</a> *@
    <a asp-action="pickedtrip_List">picked trip</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bus_number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.start_date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.end_date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.bus_number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.start_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.end_date)
            </td>
            <td>
                @* <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a> *@
                    <a asp-action="AddTrip" asp-route-id="@item.ID" class="btn btn-danger">pick</a>
            </td>
        </tr>
}
    </tbody>
</table>

BTRS/Views/User/login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@* Your Razor view *@

<style>
    form {
        display: flex;
        justify-content: space-between;
        align-items: center;
        width: 60%;
        margin: 0 auto;
    }

    .left {
        width: 50%;
    }

        .left table {
            width: 100%;
        }

        .left td {
            padding: 10px;
        }

        .left input {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            margin-bottom: 10px;
        }

    .right {
        /* Add styles for the right section if uncommented */
    }

    .btn {
        display: inline-block;
        padding: 10px 20px;
        font-size: 16px;
        cursor: pointer;
        text-align: center;
        text-decoration: none;
        outline: none;
        color: #fff;
        background-color: #007bff;
        border: none;
        border-radius: 5px;
    }

        .btn:hover {
            background-color: #0056b3;
        }

    .btn-outline-danger {
        display: inline-block;
        padding: 10px 20px;
        font-size: 16px;
        text-align: center;
        text-decoration: none;
        outline: none;
        color: #dc3545;
        border: 2px solid #dc3545;
        border-radius: 5px;
        margin-left: 10px;
    }

        .btn-outline-danger:hover {
            background-color: #dc3545;
            color: #fff;
        }</style>

@using (Html.BeginForm("login", "User", FormMethod.Post))
{
    <div class="left">
        <table>
            <tr>
                <td>username</td>
                <td>@Html.TextBox("username", null, new { type = "text" })</td>
            </tr>
            <tr>
                <td>password</td>
                <td>@Html.TextBox("password", null, new { type = "password" })</td>
            </tr>
        </table>
    </div>
    /*<div class="right">
        <img src="~/images/bus.png" alt="bus" />
    </div>*/
   // <button class="btn"><img src="~/images/bus.png" alt="bus" /></button>
    @Html.TextBox("login", "login", new { @type = "submit" })
    <a asp-action="signup" asp-controller="User" class="btn-outline-danger">signup</a>
}
@TempData["msg"]
      

BTRS/Views/User/pickedtrip_List.cshtml
@model IEnumerable<BTRS.Models.Trip>

@{
    ViewData["Title"] = "pickedTrip";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>pickedTrip</h1>

<p>
   @*  <a asp-action="Create">Create New</a> *@
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bus_number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.start_date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.end_date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.bus_number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.start_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.end_date)
            </td>
            <td>
               @*  <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |*@
                    <a asp-action="delete_picked_trip" asp-route-tripID="@item.ID" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

BTRS/Views/User/signup.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<style> .signup-form {
    width: 50%;
    margin: 0 auto;
}

.form-table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 15px;
}

.form-table td {
    padding: 10px;
    border: 1px solid #ddd;
}

.input-field {
    width: 100%;
    padding: 8px;
    box-sizing: border-box;
}

.select-field {
    width: 100%;
    padding: 8px;
    box-sizing: border-box;
}

.submit-button {
    display: inline-block;
    padding: 10px 20px;
    font-size: 16px;
    cursor: pointer;
    text-align: center;
    text-decoration: none;
    outline: none;
    color: #fff;
    background-color: #007bff;
    border: none;
    border-radius: 5px;
}

.submit-button:hover {
    background-color: #0056b3;
} </style>

@using (Html.BeginForm("signup", "User", FormMethod.Post, new { @class = "signup-form" }))
{
    <table class="form-table">

        <tr>
            <td>
                Name
            </td>
            <td>
                @Html.TextBox("name", null, new { @type = "text", @class = "input-field" })
            </td>
        </tr>
        <tr>
            <td>
                Username
            </td>
            <td>
                @Html.TextBox("username", null, new { @type = "text", @class = "input-field" })
            </td>
        </tr>
        <tr>
            <td>
                Password
            </td>
            <td>
                @Html.TextBox("password", null, new { @type = "password", @class = "input-field" })
            </td>
        </tr>
        <tr>
            <td>
                Phone Number
            </td>
            <td>
                @Html.TextBox("phone_number", null, new { @type = "text", @class = "input-field" })
            </td>
        </tr>
        <tr>
            <td>
                Email Address
            </td>
            <td>
                @Html.TextBox("email_address", null, new { @type = "text", @class = "input-field" })
            </td>
        </tr>
        <tr>
            <td>
                Gender
            </td>
            <td>
                @Html.DropDownList("gender", new SelectList(new List<string> { "Male", "Female" }), null, new { @class = "select-field" })
            </td>
        </tr>
    </table>
    @Html.TextBox("signup", "Sign Up", new { @type = "submit", @class = "submit-button" })
}

@TempData["Msg"]

BTRS/Views/User/tripOrBus.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<a asp-action="Index" asp-controller="Trip" class="btn-outline-danger">trip</a>
<a asp-action="Index" asp-controller="Bus" class="btn-outline-danger">Bus</a>